# Generated by Django 4.2.3 on 2023-07-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_auther_post_authers_post_vedio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authers',
            new_name='authors',
        ),
    ]
